name: Unit tests
on:
  pull_request:
  push:
    branches:
    - master
env:
  DJANGO_DEBUG: True
  DJANGO_ALLOWED_HOSTS: '*'
  DJANGO_SECRET_KEY: secret_key
  ES_HOSTS: localhost:9200
  CELERY_BROKER_URL: redis://localhost:6379
  SS_HOSTS: http://test:test@192.168.1.128:62081
jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python }}
    steps:
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Check out
      uses: actions/checkout@v2
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: python-${{ matrix.python }}-${{ hashFiles('requirements/test.txt') }}
    - name: Install pip dependencies
      run: pip install -r requirements/test.txt
    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
    - name: Install npm dependencies
      run: npm ci --only=prod
    - name: Run tests
      run: coverage run manage.py test
    - name: Upload coverage
      uses: codecov/codecov-action@v1
  migrations:
    runs-on: ubuntu-20.04
    name: Migrations
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: python-${{ hashFiles('requirements/test.txt') }}
    - name: Install pip dependencies
      run: pip install -r requirements/test.txt
    - name: Check migrations
      run: ./scripts/checkformigrations.sh
